services:
  - type: web
    name: mid-trust
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node dist/src/main
    envVars:
      - key: NODE_ENV
        value: production
