export const ERROR_CODES = {
  UNAUTHORIZED: 'ERR_UNAUTHORIZED',
  FORBIDDEN: 'ERR_FORBIDDEN',
  NOT_FOUND: 'ERR_NOT_FOUND',
  VALIDATION_ERROR: 'ERR_VALIDATION_FAILED',
  DUPLICATE_RESOURCE: 'ERR_DUPLICATE_RESOURCE',
  INVALID_CREDENTIALS: 'ERR_INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'ERR_TOKEN_EXPIRED',
  INVALID_WEBHOOK_SIGNATURE: 'ERR_INVALID_WEBHOOK_SIGNATURE',
  PAYMENT_ALREADY_PROCESSED: 'ERR_PAYMENT_ALREADY_PROCESSED',
  INTERNAL_ERROR: 'ERR_INTERNAL_SERVER_ERROR',
};
