export const INJECTION_TOKENS = {
  USER_REPOSITORY: 'USER_REPOSITORY',
  ROLE_REPOSITORY: 'ROLE_REPOSITORY',
  SESSION_REPOSITORY: 'SESSION_REPOSITORY',
  PATIENT_REPOSITORY: 'PATIENT_REPOSITORY',
  INVOICE_REPOSITORY: 'INVOICE_REPOSITORY',
  VIRTUAL_ACCOUNT_REPOSITORY: 'VIRTUAL_ACCOUNT_REPOSITORY',
  PAYMENT_REPOSITORY: 'PAYMENT_REPOSITORY',
  RECEIPT_REPOSITORY: 'RECEIPT_REPOSITORY',
  NOTIFICATION_REPOSITORY: 'NOTIFICATION_REPOSITORY',
  AUDIT_LOG_REPOSITORY: 'AUDIT_LOG_REPOSITORY',
  SETTING_REPOSITORY: 'SETTING_REPOSITORY',
};
